export default {
    CREATE_COURSE:"CREATE_COURSE",
    CREATE_COURSE_SUCCESS:"CREATE_COURSE_SUCCESS",
    UPDATE_COURSE:"UPDATE_COURSE",
    UPDATE_COURSE_SUCCESS:"UPDATE_COURSE_SUCCESS",
    LOAD_COURSES: "LOAD_COURSES",
    LOAD_COURSES_SUCCESS:" LOAD_COURSES_SUCCESS",
    DELETE_COURSE:"DELETE_COURSE",

    LOAD_AUTHORS:"LOAD_AUTHORS",
    LOAD_AUTHORS_SUCCESS:"LOAD_AUTHORS_SUCCESS"
}