export default {
    CREATE_COURSE:"CREATE_COURSE",
    UPDATE_COURSE:"UPDATE_COURSE",
    LOAD_COURSES: "LOAD_COURSES",
    LOAD_COURSES_SUCCESS:" LOAD_COURSES_SUCCESS",
    DELETE_COURSE:"DELETE_COURSE"
}